id: hl7.fhir.us.codi
canonical: http://hl7.org/fhir/us/codi
name: HL7FHIRImplementationGuideCODIRelease1USRealmSTU1
status: draft
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: draft
jurisdiction: urn:iso:std:iso:3166#US "null"
publisher:
  name: The MITRE Corporation
  url: https://www.mitre.org
  email: mtiller@mitre.org
dependencies:
  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.cdmh: 0.1.0
title: "HL7 FHIR Implementation Guide: CODI Data Model - US Realm | STU1"
description: The Clinical & Community Data Initiative (CODI) FHIR Implementation Guide
menu:
  Home: index.html
  Background: background.html
  Data Model: dataModel.html
  Artifacts: artifacts.html